import React from 'react';

export function getIntro() {
    const intros = 
        ["Greetings! I am Pastor AI. How can I be of assistance to you today? ",
        "Hello! It's great to hear from you. How can I pray for you today? ",
        "Hello! How can I help you today with your spiritual journey? ",
        "Hello! How can I pray for you today? Hello! ",
        "How can I be of service to you today? Hello! ",
        "It's a joy to be speaking with you. How can I pray for you today? ",
        "Hello! It's great to speak with you today. How can I be of assistance to you on your spiritual journey? ",
        "Greetings! It's a joy to be speaking with you today. May I ask what's on your mind and how I can be of help in this conversation? ",
        "Hello! It's great to have the opportunity to speak with you today. May I ask how I may assist you in your spiritual journey? ",
        "Greetings! I am Pastor AI. How may I assist you in your spiritual journey today? ",
        "Hello! It's great to connect with you today. How can I support you in your spiritual journey? ",
        "Hello! How can I be of service to you today? Greetings! It's a joy to speak with you today. How can I be of assistance to you on your spiritual journey? ",
        "Greetings! How can I support you in your spiritual journey today? ",
        "Greetings, my child! It is a joy to speak with you today. How can I be of assistance in your spiritual journey? ",
        "Hello! It's great to see you today. How can I help you with your faith journey today? ",
        "Greetings, my child! It is a joy to speak with you today. How can I be of assistance to you on your spiritual journey? ",
        "Hello! It's great to hear from you today. How can I pray for you or encourage you with the Word of God? ",
        "Hello! It's a joy to connect with you today. How can I pray for you or support you in your spiritual journey? ",
        "Greetings! It's a pleasure to meet you. How can I be of service to you today? ",
        "Hello my friend, it's great to see you today. How can I pray for you or support you in your faith journey? ",
        "Hello! It's great to meet you. How can I pray for you today? ",
        "Greetings! It is a joy to speak with you today. ",
        "How can I be of assistance in your spiritual journey? ",
        "Greetings! It is a joy to speak with you today. How may I be of assistance in your spiritual journey? ",
        "Hello! It's great to meet you. How can I support you in your spiritual journey today? ",
        "Hello! It is a joy to speak with you today. How can I support you in your spiritual journey? ",
        "Greetings! It's great to see you today. How can I support you in your spiritual journey? ",
        "Hello! How can I be of service to you today? ",
        "Greetings! I am Pastor AI. How can I be of service to you today? ",
        "May I pray for you or offer you any words of comfort from the Bible? ",
        "Hello there! It's great to meet you. How can I be of assistance to you today? ",
        "Greetings! How can I serve you in your spiritual journey today? ",
        "Hello! It's great to connect with you. How can I be of assistance to you today? ",
        "Hello! I'm Pastor AI, how can I be a blessing to you today? ",
        "Hello! I hope this day finds you well. May I ask how I may be of assistance to you in your spiritual journey? ",
        "Greetings! I am Pastor AI. How can I help you today? ",
        "Greetings! I am Pastor AI. How may I be of assistance to you today? ",
        "Hello! It's great to have the opportunity to speak with you today. How can I be of assistance to you in your walk with the Lord? ",
        "Hello! It's great to see you today! How can I help you with your spiritual journey? ",
        "Hello! It's great to connect with you today. How can I be of assistance to you on your spiritual journey? ",
        "Greetings, friend! It is a joy to speak with you. How can I be of assistance in your spiritual journey today? ",
        "Hello! I'm Pastor AI. It's a pleasure to meet you. How can I help you today? ",
        "Hello! How can I be of service to you today? Greetings! I am Pastor AI, it's a pleasure to meet you. ",
        "How can I assist you on your spiritual journey today? ",
        "Hello! I am Pastor AI. How may I be of service to you today? ",
        "Hello! It's great to connect with you today. What's on your mind? ",
        "Hello! It's great to be speaking with you. How can I be of service to you today? ",
        "Hello my friend! How can I be of assistance to you today? I am here to offer guidance and support based on the teachings of the Bible. ",
        "Hello! It's a pleasure to meet you. May God bless you today and always. How can I assist you in your spiritual journey? ",
        "Greetings! It's a blessing to be able to communicate with you today. How can I assist you in your spiritual journey? Hello! It's a joy to speak with you today. How can I be of assistance to you?",
        ];
        return intros[Math.floor(Math.random() * intros.length)];
}